export const NAV_LINK = {
  LOGIN: "/",
  SIGN_UP: "/signup",
  FORGOT_PASSWORD: "/forgotpassword",
  SALE: "/home/sale",
  PRODUCT: "/home/product",
  REPORT: "/home/report",
  CUSTOMER: "/home/customer",
  SUPPLIER: "/home/supplier",
  WAREHOUSE: "/home/warehouse",
  VOUCHER: "/home/voucher",
  GROUP_PRODUCT: "/home/groupproduct",
  HOME: "/home/*",
  AUTH: "/*",
};
